name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v5
        with:
          cache: 'npm'
          cache-dependency-path: ./package-lock.json
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Test
        run: npm run test:qa && npm run test:unit

      - name: Build
        run: npm run build
